on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    name: Token Run
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Perform token run
        run: |
          echo $(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=gha-medium" | base64)
        shell: bash
