on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Generate JWT Token
        id: jwt
        run: |
          # Perform any necessary steps to generate the JWT token
          # For this example, we'll use a dummy token
          echo "::set-output name=token::dummy_token_123"

      - name: Print JWT Token
        run: echo "Generated JWT token: ${{ steps.jwt.outputs.token }}"
