name: Generate JWT

on:
  workflow_dispatch:

jobs:
  generate-jwt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate JWT
        run: |
          echo -n "${{ secrets.PRIVATE_KEY }}" > private_key.pem
          printf '{"alg": "RS256", "typ": "JWT"}\n%s\n' "${{ secrets.JWT_PAYLOAD }}" | base64 | tr -d '\n' > headers_payload.base64
          openssl dgst -sha256 -sign private_key.pem -out jwt_signature.bin headers_payload.base64
          base64 jwt_signature.bin | tr -d '\n' > jwt_signature.base64
          printf "%s.%s" $(cat headers_payload.base64) $(cat jwt_signature.base64) > jwt_token

      - name: Display JWT
        run: |
          cat jwt_token