name: Generate JWT

on:
  workflow_dispatch:

jobs:
  generate-jwt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Generate JWT
        run: |
          export PRIVATE_KEY="${{ secrets.PRIVATE_KEY }}"
          export JWT_PAYLOAD="${{ secrets.JWT_PAYLOAD }}"
          
          echo "$PRIVATE_KEY" > private.key
          
          # Install required dependencies (jsonwebtoken)
          npm install jsonwebtoken
          
          # Generate the JWT
          node -e '
          const fs = require("fs");
          const jwt = require("jsonwebtoken");
          
          const privateKey = fs.readFileSync("private.key", "utf8");
          const payload = JSON.parse(process.env.JWT_PAYLOAD);
          
          const token = jwt.sign(payload, privateKey, { algorithm: "RS256" });
          console.log(token);
          ' > jwt.token

      - name: Display JWT
        run: cat jwt.token