on: [push]

jobs:
  send:
    name: Send new version
    runs-on: ubuntu-latest
    steps:
      - name: JWT Generator
        id: jwtGenerator
        uses: morzzz007/github-actions-jwt-generator@1.0.1
        with:
          secret: topsecret
          payload: '{"hello":"world"}'

      - name: Set Token
        run: echo "TOKEN=${{ steps.jwtGenerator.outputs.token }}" >> $GITHUB_ENV

      - name: Display Token
        run: echo $TOKEN | base64 --decode
