name: Generate JWT Token

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    name: Says Hello World
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Perform token run
        run: |
          echo $(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=gha-medium" "test" | base64)
        shell: bash
