name: Generate JWT Token

on:
  push:
    branches:
      - main


jobs:
  send:
    name: Send new verison
    runs-on: ubuntu-latest
    steps:
      - name: JWT Generator
        id: jwtGenerator
        uses: morzzz007/github-actions-jwt-generator@1.0.1
        with:
          secret: topsecret
          payload: '{"hello":"world"}'
      - name: DUMP Token
        run: echo ${{steps.jwtGenerator.outputs.token}} > test.txt
      - name: test2
        run: echo 'test' > test2.txt
      - name: read txt
        run: cat test.txt
      - name: read2 txt
        run: cat test2.txt
