name: Generate JWT Token

on:
  push:
    branches:
      - main
env:
  hashiUrl: https://localhost:8081
  roleName: gha-test-role
  audience: gha-medium
jobs:
  hello:
    runs-on: ubuntu-latest
    name: Says Hello World
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Perform token run
        run: |
          echo $(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=gha-medium" | base64)
        shell: bash
      - name: Retrieve Vault Secrets
        id: retrieve-secrets
        uses: hashicorp/vault-action@v2.7.2
        with:
          url: ${{ env.hashiUrl }}
          role: ${{ env.roleName }}
          method: jwt
          jwtGithubAudience: ${{ env.audience }}
          tlsSkipVerify: false
          exportEnv: false
          secrets: |
            secret/data/apikeys deploymentServer | DEPLOYMENT_KEY